### ISSUE TITLE
Here is a challenge :D

### ISSUE THREAD

**Issue by crgimenes** [cassiobotaro/60-days-of-go#2]
You are working on a project that exchanges files with an old system. 
The problem is that this system is so old that it uses ASCII 7-bits and the files you get are 7 bits per character instead of 8 bits per character.

Your mission is to create a functions that reads 7bits files and converts to the modern 8bits standard and vice versa.

I know I'm going straight to hell! Good hack :D

**Comment by cassiobotaro** [comment]
60 days finnished, this challenge is cool but have some tricks, i'll try to do that in another moment, thanks @crgimenes !
